# Generated by Django 5.0.6 on 2026-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_participantuser_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='discord_handle',
            field=models.CharField(blank=True, help_text='Optional Discord username for team matching', max_length=100),
        ),
        migrations.AlterField(
            model_name='participantuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
