# Generated by Django 5.0.6 on 2026-06-09 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_discord_handle_alter_participantuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resources_text', models.TextField(blank=True, help_text='Links, notes, or extra info shown to assigned teams')),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='challenge_resources/')),
                ('max_teams', models.PositiveIntegerField(default=3, help_text='Maximum number of teams that can work on this challenge')),
                ('is_published', models.BooleanField(default=False, help_text='Make visible to participants')),
                ('assignment_published', models.BooleanField(default=False, help_text='Show team assignments to participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from organizers to the team')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='registrations.challenge')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_assignment', to='registrations.team')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('prio1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_prio1', to='registrations.challenge')),
                ('prio2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_prio2', to='registrations.challenge')),
                ('prio3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref_prio3', to='registrations.challenge')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_preference', to='registrations.team')),
            ],
        ),
    ]
