# Generated by Django 5.0.6 on 2026-06-09 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_challenge_challengeassignment_challengepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_label', models.CharField(help_text='e.g. "09:00" or "09:00–09:30"', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('day', models.PositiveIntegerField(default=1, help_text='Day number (1 = Day 1, 2 = Day 2, …)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_highlight', models.BooleanField(default=False, help_text='Show in accent colour')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['day', 'order', 'time_label'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='preference_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for teams to submit preferences (leave blank = no deadline)', null=True),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_url', models.URLField(blank=True, help_text='GitHub / GitLab repo link')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo or video link')),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='submissions/pitch_decks/')),
                ('additional_file', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('notes', models.TextField(blank=True, help_text='Any notes for the jury')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='registrations.team')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
