# Generated by Django 5.0.6 on 2026-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_scheduleitem_challenge_preference_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='preference_deadline',
        ),
        migrations.AddField(
            model_name='challenge',
            name='deep_dive',
            field=models.TextField(blank=True, help_text='Technical/detailed background — shown in detail view'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='judging_criteria',
            field=models.TextField(blank=True, help_text='How submissions will be judged (shown in detail view)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='short_description',
            field=models.TextField(blank=True, help_text='1–2 sentence teaser shown on the card'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='sponsor_description',
            field=models.TextField(blank=True, help_text='Short description of the sponsor company'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preference_deadline',
            field=models.DateTimeField(blank=True, help_text='Global deadline for case preference submissions (leave blank = no deadline)', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, help_text='Full challenge description'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='resource_file',
            field=models.FileField(blank=True, help_text='File only shown to assigned teams after assignment is published', null=True, upload_to='challenge_resources/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='resources_text',
            field=models.TextField(blank=True, help_text='Links, notes — only shown to assigned teams after assignment is published'),
        ),
    ]
