# Generated by Django 5.0.6 on 2026-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_remove_challenge_preference_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for project submissions (leave blank = no deadline)', null=True),
        ),
    ]
