# Generated by Django 5.0.6 on 2026-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_sitesettings_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='date',
            field=models.DateField(blank=True, help_text='Date of this schedule item (e.g. 2026-11-07)', null=True),
        ),
    ]
